FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY ["dotnetapi/TestLib/TestLib.csproj", "dotnetapi/TestLib/"]
COPY ["dotnetapi/EchoService/EchoService.csproj", "dotnetapi/EchoService/"]
#COPY *.csproj ./
RUN dotnet restore "dotnetapi/EchoService/EchoService.csproj"

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "EchoService.dll"]
